### PR TITLE
remove outdated IOC disclaimer from CSR intro

### PR DESCRIPTION
**Pull request by CamrynCarter**

### CODE REVIEW

**Review by clanktron — COMMENTED** [review]
LGTM, but not sure how @atoy3731/@bgulla feel about removing the DOD/CNCF links.

**Comment by clanktron** [comment]
Also looks like you included these changes in all your other PRs, so might want to remove it from those.

**Comment by CamrynCarter** [comment]
> Also looks like you included these changes in all your other PRs, so might want to remove it from those.

Fixed now in other PRs

**Comment by CamrynCarter** [comment]
> LGTM, but not sure how @atoy3731 / @bgulla feel about removing the DOD/CNCF links.

The links should still be there? Unless I messed something up, which is possible :)

**Review by amartin120 — APPROVED** [review]
LGTM

**Pull request merged**
